stages:
  - test
  - artifacts

variables:
  path_to_test_report_directory: "${CI_PROJECT_DIR}/test-reports/"

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $APP_UNDER_TEST_IMAGE
    - docker run -d -p 8000:8000 $APP_UNDER_TEST_IMAGE php -S 0.0.0.0:8000

    - apk add curl
    - curl http://docker:8000

    - docker pull $UI_TESTS_IMAGE
    - docker run --net="host" --name playwright-cucumber-js-docker $UI_TESTS_IMAGE /bin/bash -c "npm run test:normal && npm run report"
    - docker cp playwright-cucumber-js-docker:/app/reports/cucumber_report.html test-reports/cucumber_report.html
    - mv test-reports/cucumber_report.html test-reports/$(date "+%Y.%m.%d-%H.%M.%S")_cucumber_report.html

  artifacts:
    paths:
      - $path_to_test_report_directory
    expire_in: 1 week
